modLoader = "kotlinforforge"
loaderVersion = "[5.3,)"
license = "MIT"
issueTrackerURL = "https://github.com/Erdragh/KAI/issues"

[[mods]]
modId = "kai"
version = "1"
displayName = "KAI"
displayURL = "https://modrinth.com/mod/kai"
logoFile = "icon.png"
authors = "Erdragh"
description = "${description}"

[[dependencies.kai]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kai]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"