modLoader = "kotlinforforge"
loaderVersion = "${kotlinForgeRange}"
license = "${license}"
issueTrackerURL = "https://github.com/Erdragh/KAI/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "https://modrinth.com/mod/kai"
logoFile = "icon.png"
authors = "${mod_author}"
description = "${description}"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraftVersionRange}"
ordering = "NONE"
side = "BOTH"